In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [11]:
%matplotlib inline

import numpy as np
import pandas as pd
import geopandas as gpd
import fiona

pd.options.display.max_rows = 15

In [4]:
bldg = gpd.read_file('C:\GIS Open Source\Python\RasterProcessing\Bldg_footprints.shp')
bldg.head()

,PIN,PARNUM,CARDNUM,BLDGNUM,STNUM,STPRE,STNAME,STTYPE,STSUF,UNITNUM,UNITS,BTYPE,Shape_area,Shape_len,DIST,geometry
0,547450040972,19,01,None,2891,None,DONEGAL,DR,None,None,1.0,4,2199.520986,203.308365,12,"POLYGON ((2575190.027032033 440602.3359100968,..."
1,547450040972,97,01,None,6536,None,LETTER KENNY,LN,None,None,1.0,4,2168.314391,202.478562,12,"POLYGON ((2574831.82138361 440681.4604237676, ..."
2,548617403662,8,01,None,717,None,DORSET,RD,None,C,1.0,4,2492.073124,227.296670,02,"POLYGON ((2581676.403823018 467260.6825276911,..."
3,548617403662,11,01,None,705,None,DORSET,RD,None,D,1.0,4,2400.299139,220.389378,02,"POLYGON ((2581813.955057114 467128.8153373599,..."
4,548617403662,18,01,None,714,None,DORSET,RD,None,F,1.0,4,2505.972377,229.547095,02,"POLYGON ((2581511.112486944 466962.1221011877,..."

In [8]:
#Since I don't know the exact height of each building, I will give them a random number selected from a reasonable range

bldg['randHeight'] = np.random.randint(20, 200, bldg.shape[0])

In [9]:
bldg.randHeight.mean()

109.58576714682172

In [10]:
bldg.head()

,PIN,PARNUM,CARDNUM,BLDGNUM,STNUM,STPRE,STNAME,STTYPE,STSUF,UNITNUM,UNITS,BTYPE,Shape_area,Shape_len,DIST,geometry,randHeight
0,547450040972,19,01,None,2891,None,DONEGAL,DR,None,None,1.0,4,2199.520986,203.308365,12,"POLYGON ((2575190.027032033 440602.3359100968,...",76
1,547450040972,97,01,None,6536,None,LETTER KENNY,LN,None,None,1.0,4,2168.314391,202.478562,12,"POLYGON ((2574831.82138361 440681.4604237676, ...",179
2,548617403662,8,01,None,717,None,DORSET,RD,None,C,1.0,4,2492.073124,227.296670,02,"POLYGON ((2581676.403823018 467260.6825276911,...",43
3,548617403662,11,01,None,705,None,DORSET,RD,None,D,1.0,4,2400.299139,220.389378,02,"POLYGON ((2581813.955057114 467128.8153373599,...",127
4,548617403662,18,01,None,714,None,DORSET,RD,None,F,1.0,4,2505.972377,229.547095,02,"POLYGON ((2581511.112486944 466962.1221011877,...",175

In [12]:
#Save it back to shapefile

bldg.to_file('C:\GIS Open Source\Python\RasterProcessing\BuildingWithHeight.shp')